### ISSUE TITLE
Home Assistant Mosquitto Integration Issue

### ISSUE THREAD

**Issue by prahjister** [arendst/Sonoff-MQTT-OTA-Arduino#111]
I am having some major issues with getting integration to work and I do not know where to start troublehoot.

I am running Home Assistant and Mosquitto on a Windows 10 box. Both appear to be the latest and installed ok.

Here is my sonoff config.

```
light:
  platform: mqtt
  name: "Living Room Light"
  state_topic: "stat/sonoff/POWER"
  command_topic: "cmnd/sonoff/power"
  payload_on: "ON"
  payload_off: "OFF"
```
and my mqtt config

```
mqtt:
  broker: 10.0.0.200
  port: 1883
  client_id: home-assistant-1
```

sonoff device config

![image](https://cloud.githubusercontent.com/assets/11030902/20834193/fc1e863e-b861-11e6-9094-16e7c18c8e0b.png)

When I compiled and uploaded the only thing i changed was my ssid and password.

Here are my symptoms.

I can turn the relay on and off fine from an app on my phone called mymqtt. It successfully connects. And if I publish a 1 or 0 to cmnd/sonoff/power from the app.

When I press the button on the sonoff the relay works. but neither the mymqtt app shows status nor home assistant.

On the Home Assistant states page if the light is on I can press the toggle and it turns off. I can see the on request on the mymqtt app. If I try to turn it on with the toggle sonoff blinks but does nothing.

Any help is appreciated. I have spent a lot of time troubleshooing. Did a lot of reading but this is as far as i have got.

**Comment by arendst** [comment]
What happens if you change ```state_topic``` in ```stat/sonoff/1/POWER```

**Comment by prahjister** [comment]
I am not positive where you want me to change...in the arduino code? I did try in the home assistance config and now no state change even with phone.

**Comment by arendst** [comment]
In your home assistance config.

Just try a basic mosquitto command like  ```mosquitto_pub -t cmnd/sonoff/POWER -m 2```
 and monitor with  ```mosquitto_sub -t stat/# -t tele/# -t cmnd/# -v```

**Comment by prahjister** [comment]
Seems to work. I have an output and everything works as expected. But when i pressButton on sonoff only show stat and no cmnd when pressing the button on the device. Phone works as expected. I did put home assistance config back. 

tat/sonoff/1/POWER OFF
cmnd/sonoff/power 1
stat/sonoff/POWER ON
cmnd/sonoff/power 2
stat/sonoff/POWER OFF
cmnd/sonoff/power 0
stat/sonoff/POWER OFF
cmnd/sonoff/power 2
stat/sonoff/POWER ON
stat/sonoff/1/POWER OFF
stat/sonoff/1/POWER ON
stat/sonoff/1/POWER OFF

**Comment by prahjister** [comment]
i see....it is mixing stat

**Comment by arendst** [comment]
Pressing the button is not a command so you won't see a ```cmnd``` UNLESS you configured ButtonTopic in which case the button will send a MQTT command and you have to act on it. 

Forget about ButtonTopic now and focus on the return stat value. The sonoff software works as designed. Your Home assistance script needs some tweeking.

**Comment by prahjister** [comment]
i was under the impression that i could use the button on the sonoff to turn the relay on and off.

**Comment by prahjister** [comment]
and why does it return status on stat/sonoff/1/.......is there a way i can modify to remove the 1

**Comment by arendst** [comment]
Well you do.

Start from the beginning (ButtonTopic = 0):
- Press button and relay toggles - Mqtt response: ```stat/sonoff/1/POWER ON```
- Press button and relay toggles - Mqtt response: ```stat/sonoff/1/POWER OFF```

And no you can't remove the one. It is needed in sonoff dual and future devices to distinguish between relays.

**Comment by arendst** [comment]
Just send mqtt commands with the one too like ```cmnd/sonoff/1/POWER 1``` and all is well.

**Comment by prahjister** [comment]
Almost 100% I really appreciate your help....Button now works on the sonoff...
only thing that doesn't seem to work as I expect then is when I send an "ON" it doesn't turn on. Only with numbers.

**Comment by arendst** [comment]
What happens with command ``` mosquitto_pub -t cmnd/sonoff/POWER -m ON```

Mine works.

**Comment by arendst** [comment]
Ah you're right with the 1 in it it doesn't. I'll investigate...

**Comment by arendst** [comment]
Solved in next version soon to be released.

**Comment by prahjister** [comment]
Awesome...once confirmed I will post working config for newbies like me to this. Hopefully save them some frustration.

**Comment by arendst** [comment]
New version released. Please confirm.

**Comment by prahjister** [comment]
Perfect...so here is the final config. Now to figure out Home Assistant.....I wish there was an easier way to automate...

```
light:
  platform: mqtt
  name: "Living Room Light"
  state_topic: "stat/sonoff/1/POWER"
  command_topic: "cmnd/sonoff/1/power"
  payload_on: "ON"
  payload_off: "OFF"
```

```
mqtt:
  broker: 10.0.0.200
  port: 1883
  client_id: home-assistant-1
```
![image](https://cloud.githubusercontent.com/assets/11030902/20838024/b5bd2070-b874-11e6-895b-1beed6f896c5.png)
