### ISSUE TITLE
Home Assistant / MQTT switching back when manually toggled

### ISSUE THREAD

**Issue by loxK** [arendst/Sonoff-MQTT-OTA-Arduino#333]
Version: Sonoff-Tasmota 5.12.0

I have devices set this way:

```
switch:
    - platform: mqtt
      name: "sonoffp_server"
      state_topic: "stat/sonoffp-server/POWER"
      command_topic: "cmnd/sonoffp-server/POWER"
      available_topic: "tele/sonoffp-server/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: true
```

Whenever I manually toggle the switch using the sonoff physical button, it work but a few seconds after it is "magically" switched back to initial position. Any idea of why ?
