### ISSUE TITLE
Configuring Home Assistant

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-MQTT-OTA-Arduino#64]
Has anyone successfully configured Home Assistant?

I've tried the following:
```
switch:
  - platform: mqtt
    name: "Bedroom Fan"
    state_topic: "stat/sonoff1/power"
    command_topic: "cmnd/sonoff1/power"
    payload_on: "ON"
    payload_off: "OFF"
```
But it seems that this cannot tell the state of the switch and is only capable of powering it on, and not off. Anyone know what I might be doing wrong here?

Here's the documentation for mqtt-switch:

https://home-assistant.io/components/switch.mqtt/
